version: '2'

services:

  selenium-chrome:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"

  bbt:
    build: .
    environment:
      - SELENIUM_HOST=selenium-chrome
      - SELENIUM_PORT=4444
    depends_on:
      - selenium-chrome
