version: '2'

services:

  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    logging:
      driver: none

  selenium-chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub

  bbt:
    build: .
    environment:
      - SELENIUM_HOST=selenium-chrome
      - SELENIUM_PORT=4444
    depends_on:
      - selenium-chrome
      - hub
